name: Run tests and upload coverage

on: 
  push

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸  Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: ğŸ—  Set up Poetry
        run: pipx install poetry
      - name: ğŸ—  Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: ğŸ—  Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: ğŸ—  Install dependencies
        run: poetry install --no-interaction
      - name: Run tests
        run: poetry run pytest --cov
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
 
